import { TreasuryAlertPayload, WorkerNotificationPayload } from "../notifier/notifier";

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#039;");

const formatTokens = (amount: number): string =>
  Number.isFinite(amount) ? (amount / 1e7).toFixed(2) : "N/A";

const formatDate = (iso: string | null | undefined): string => {
  if (!iso) return "N/A";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "N/A";
  return d.toISOString().replace("T", " ").replace("Z", " UTC");
};

const baseLayout = (title: string, body: string): string => `
  <div style="font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; line-height: 1.4;">
    <h2 style="margin: 0 0 12px;">${escapeHtml(title)}</h2>
    <div style="margin: 0 0 16px; color: #111827;">${body}</div>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;" />
    <div style="font-size: 12px; color: #6b7280;">
      This alert was generated by Quipay. Do not reply to this email.
    </div>
  </div>
`;

export const renderTreasuryLowRunwayEmail = (
  payload: TreasuryAlertPayload,
): { subject: string; html: string } => {
  const runway =
    payload.runway_days !== null ? `${payload.runway_days.toFixed(1)} days` : "unlimited";

  const body = `
    <p><strong>Employer:</strong> ${escapeHtml(payload.employer)}</p>
    <p><strong>Runway:</strong> ${escapeHtml(runway)}</p>
    <p><strong>Balance:</strong> ${escapeHtml(formatTokens(payload.balance))} tokens</p>
    <p><strong>Liabilities:</strong> ${escapeHtml(formatTokens(payload.liabilities))} tokens</p>
    <p><strong>Daily burn rate:</strong> ${escapeHtml(formatTokens(payload.daily_burn_rate))} tokens/day</p>
    <p><strong>Funds exhaustion date:</strong> ${escapeHtml(formatDate(payload.funds_exhaustion_date))}</p>
    <p><strong>Threshold:</strong> ${escapeHtml(String(payload.alert_threshold_days))} days</p>
    <p style="margin-top: 16px;"><strong>Timestamp:</strong> ${escapeHtml(formatDate(payload.timestamp))}</p>
  `;

  return {
    subject: "Treasury low runway alert",
    html: baseLayout("Treasury Low Runway Alert", body),
  };
};

export const renderWorkerCliffUnlockEmail = (
  payload: WorkerNotificationPayload,
): { subject: string; html: string } => {
  const body = `
    <p><strong>Worker:</strong> ${escapeHtml(payload.worker)}</p>
    <p><strong>Employer:</strong> ${escapeHtml(payload.employer)}</p>
    <p><strong>Stream ID:</strong> ${escapeHtml(String(payload.stream_id))}</p>
    <p><strong>Token:</strong> ${escapeHtml(payload.token)}</p>
    <p><strong>Cliff unlock date:</strong> ${escapeHtml(formatDate(payload.cliff_date))}</p>
    <p style="margin-top: 16px;"><strong>Timestamp:</strong> ${escapeHtml(formatDate(payload.timestamp))}</p>
  `;

  return {
    subject: "Cliff unlock notification",
    html: baseLayout("Cliff Unlock", body),
  };
};

export const renderWorkerStreamEndingEmail = (
  payload: WorkerNotificationPayload,
): { subject: string; html: string } => {
  const body = `
    <p><strong>Worker:</strong> ${escapeHtml(payload.worker)}</p>
    <p><strong>Employer:</strong> ${escapeHtml(payload.employer)}</p>
    <p><strong>Stream ID:</strong> ${escapeHtml(String(payload.stream_id))}</p>
    <p><strong>Token:</strong> ${escapeHtml(payload.token)}</p>
    <p><strong>Stream end date:</strong> ${escapeHtml(formatDate(payload.stream_end_date))}</p>
    <p><strong>Total amount:</strong> ${escapeHtml(payload.amount != null ? String(payload.amount) : "N/A")}</p>
    <p style="margin-top: 16px;"><strong>Timestamp:</strong> ${escapeHtml(formatDate(payload.timestamp))}</p>
  `;

  return {
    subject: "Stream ending notification",
    html: baseLayout("Stream Ending", body),
  };
};

export const renderWorkerLowRunwayEmail = (
  payload: WorkerNotificationPayload,
): { subject: string; html: string } => {
  const body = `
    <p><strong>Worker:</strong> ${escapeHtml(payload.worker)}</p>
    <p><strong>Employer:</strong> ${escapeHtml(payload.employer)}</p>
    <p><strong>Stream ID:</strong> ${escapeHtml(String(payload.stream_id))}</p>
    <p><strong>Token:</strong> ${escapeHtml(payload.token)}</p>
    <p><strong>Runway:</strong> ${
      payload.runway_days != null ? escapeHtml(payload.runway_days.toFixed(1)) : "N/A"
    } days</p>
    <p><strong>Threshold:</strong> ${
      payload.threshold_days != null ? escapeHtml(String(payload.threshold_days)) : "N/A"
    } days</p>
    <p style="margin-top: 16px;"><strong>Timestamp:</strong> ${escapeHtml(formatDate(payload.timestamp))}</p>
  `;

  return {
    subject: "Low runway worker alert",
    html: baseLayout("Low Runway Alert", body),
  };
};

